# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0003_auto_20170725_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='y',
        ),
    ]
