# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0004_remove_graph_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('formula', models.TextField(default='x', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='graph',
            name='y',
            field=models.TextField(default=0, max_length=100),
        ),
    ]
